name: Build ISO

on:
  push:
    branches:
      - main

jobs:
  build-wallet:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 10
          cache: true

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: lts/*
          cache: "pnpm"
          cache-dependency-path: wallet/pnpm-lock.yaml

      - name: Setup Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Build Wallet Binary
        run: |
          cd wallet
          pnpm install
          pnpm tauri build

      - name: Upload Wallet Binary
        uses: actions/upload-artifact@v6
        with:
          name: wallet-binary
          path: wallet/src-tauri/target/release/app

  build-img:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs: build-wallet

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Mkosi
        uses: systemd/mkosi@v26

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install Dependencies
        run: |
          pip install pefile
          sudo apt install -y mtools

      - name: Download Wallet Binary
        uses: actions/download-artifact@v6
        with:
          name: wallet-binary
          path: ./wallet/src-tauri/target/release/app

      - name: Build IMG
        run: mkosi

      - name: Verify IMG exists
        run: ls

      - name: Upload IMG to Release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: |
            cold-usb.img
            cold-usb.img.sha256
